### ISSUE TITLE
Can not restore my encrypted snapshot

### ISSUE THREAD

**Issue by ycyr** [aiven/encrypted-repository-opensearch#29] opened 2022-06-17 19:59 UTC
Hi, I’m testing your plugin to encrypt my snapshot in AWS S3.  The snapshot process  is working  as expected. I can see all snapshots in the S3 repository.

But when I’m trying to restore the encrypted snapshot, the restore seem to be stuck and all the nodes where the shards are restored,  have JVM memory issues.

I've tried with Opensearch version 1.3.2 and version 2.0.0

In the log we can see kind of messages

[2022-06-17T19:42:39,384][INFO ][o.o.m.j.JvmGcMonitorService] [opensearch-node2] [gc][913] overhead, spent [259ms] collecting in the last [1s]
[2022-06-17T19:42:40,386][INFO ][o.o.m.j.JvmGcMonitorService] [opensearch-node2] [gc][914] overhead, spent [324ms] collecting in the last [1s]
[2022-06-17T19:42:41,388][INFO ][o.o.m.j.JvmGcMonitorService] [opensearch-node2] [gc][915] overhead, spent [286ms] collecting in the last [1s]
[2022-06-17T19:42:42,389][INFO ][o.o.m.j.JvmGcMonitorService] [opensearch-node2] [gc][916] overhead, spent [295ms] collecting in the last [1s]
[2022-06-17T19:42:43,391][INFO ][o.o.m.j.JvmGcMonitorService] [opensearch-node2] [gc][917] overhead, spent [309ms] collecting in the last [1s]
[2022-06-17T19:42:44,394][INFO ][o.o.m.j.JvmGcMonitorService] [opensearch-node2] [gc][918] overhead, spent [315ms] collecting in the last [1s]
[2022-06-17T19:42:45,397][INFO ][o.o.m.j.JvmGcMonitorService] [opensearch-node2] [gc][919] overhead, spent [318ms] collecting in the last [1s]

**Comment by willyborankin** [comment] 2022-06-29 18:43
Hi @ycyr  thank you for reporting the issue, will take a look.

**Comment by willyborankin** [comment] 2022-06-29 18:55
@ycyr what is the size of the snapshot?

**Comment by ycyr** [comment] 2022-06-30 14:56
Hi @willyborankin , thanks for your reply.  The size of our daily snapshot is around 300-500Gig but I've tried to restore index with a size of 10gig. Our data node have heap size of 31g and according to Elasticsearch official documentation we can not use above 32g ([https://www.elastic.co/guide/en/elasticsearch/reference/7.10/important-settings.html#heap-size-settings](url)). Because of that, I pretty sure it's not a JVM memory issue.

I've also tried to restore a small index (150 meg) with in a lab setup based on this page (https://opensearch.org/downloads.html](url)) with the same behavior.

Concerning the crypto provider, the documentation is not very clear on about it, so I'm not sure about it. Can you provide me more information about this setting ?

**Comment by willyborankin** [comment] 2022-06-30 17:44
> Hi @willyborankin , thanks for your reply. The size of our daily snapshot is around 300-500Gig but I've tried to restore index with a size of 10gig. Our data node have heap size of 31g and according to Elasticsearch official documentation we can not use above 32g ([https://www.elastic.co/guide/en/elasticsearch/reference/7.10/important-settings.html#heap-size-settings](url)). Because of that, I pretty sure it's not a JVM memory issue.
> 

Looks like a memory leak so it will take some time to fix. 

> I've also tried to restore a small index (150 meg) with in a lab setup based on this page ([https://opensearch.org/downloads.html](url)](https://opensearch.org/downloads.html%5D(url))) with the same behavior.
> 
> Concerning the crypto provider, the documentation is not very clear on about it, so I'm not sure about it. Can you provide me more information about this setting ?

It is possible to set 3rd party crypto provider but as far as I can see you use the default one BouncyCastle.
But for that you need to add jar manually

**Comment by ycyr** [comment] 2022-06-30 18:08
Hi @willyborankin, 

- I add AmazonCorrettoCryptoProvider jar (version 1.6.1) in the plugin directory,
-  I add  the  Java property  the flag -Djava.security.properties=/path/to/amazon-corretto-crypto-provider.security 
-  I and set encrypted.security_provider parameter to com.amazon.corretto.crypto.provider.AmazonCorrettoCryptoProvider in opensearch.yml.   

Unfortunately,  the behavior is the same  when I'm trying to restore.   

The restored index seems to be stuck to 0% of recovery after 10 min.

**Comment by willyborankin** [comment] 2022-06-30 18:17
Hi @ycyr , thank you will investigate. Definitely something strange.

**Comment by willyborankin** [comment] 2022-06-30 18:17
Will try to fix it ASAP.

**Comment by ycyr** [comment] 2022-06-30 18:39
Yes, it is possible, but its size is about 100M  (compressed).  Do you have a place where I can upload it ?

**Comment by willyborankin** [comment] 2022-06-30 18:48
Yes I have, what about Google Drive, if you see my e-mail in the profile you can share with me it not `wilyborankin at gmail.com` (I will remove this message later :-)) or I can prepare a folder in my drive and give a permit for you.

**Comment by ycyr** [comment] 2022-06-30 18:50
ok

**Comment by willyborankin** [comment] 2022-07-02 17:23
Hi @ycyr, I tried to reproduce this problem, but failed. Cannot confirm that this is a bug.

**Comment by ycyr** [comment] 2022-07-04 13:42
Hi @willybora, no problems, what kind of information you would like ?

**Comment by willyborankin** [comment] 2022-07-04 14:20
How many shards do you have in case of big amount of shards you need more memory, since each shards will be restored.  
I tested 1 index size of 12GB with 3 shards on 1 node cluster 1 GB of memory, took  heap dump before after and during restoration of snapshotting no sign of memory/recourse leak.

BTW `[2022-06-17T19:42:39,384][INFO ][o.o.m.j.JvmGcMonitorService] [opensearch-node2] [gc][913] overhead, spent [259ms] collecting in the last [1s]` - shows that your process has ~ 1GB of memory. OpenSearch starts cleaning memory in case all available memory occupied on 85%.

**Comment by ycyr** [comment] 2022-07-04 16:14
Hi @willyborankin,  

- I'm trying to recover an index of 460Meg 1 shard
- GET /_cat/recovery/restored_network-2022.06.19  after 10 minutes
 
restored_network-2022.06.19 0 10.2m snapshot index n/a n/a 172.20.71.37 cluster-ti-data-3 aws-s3-encrypted-new test4 71 0 0.0% 71 482166959 0 0.0% 482166959 0 0 100.0%

- Logs:

_[2022-07-04T12:03:49,679][INFO ][o.o.r.e.EncryptedRepository] [cluster-ti-data-3] Restore encryption data_                                                                                                                                                         
_[2022-07-04T12:03:50,790][INFO ][o.o.i.b.HierarchyCircuitBreakerService] [cluster-ti-data-3] attempting to trigger G1GC due to high heap usage [3071279104]_
_[2022-07-04T12:03:50,852][INFO ][o.o.i.b.HierarchyCircuitBreakerService] [cluster-ti-data-3] GC did bring memory usage down, before [3071279104], after [493357056], allocations [95], duration [62]_
_[2022-07-04T12:08:04,741][INFO ][o.o.j.s.JobSweeper       ] [cluster-ti-data-3] Running full sweep_                                                                                                                                                                
                                                                                                                                                                                                                                                                                      



**_Repository setting_**

PUT _snapshot/aws-s3-encrypted-new
{
    "type" : "encrypted",
    "settings" : {
      "storage_type": "s3",  
      "bucket" : "XXXXXXXX",
      "client" : "default",
      "endpoint": "s3.ca-central-1.amazonaws.com",
      "region": "ca-central-1", 
      "readonly": false
    }  
  }


**_Restore command used_**

POST _snapshot/aws-s3-encrypted-new/test4/_restore
{
  "indices": "network-2022.06.19",
  "ignore_unavailable": true,
  "include_global_state": false,
  "partial": false,
  "rename_pattern": "(.+)",
  "rename_replacement": "restored_$1",
  "index_settings": {
  "index.blocks.read_only": false,
        "number_of_replicas" : "0"
  },
  "ignore_index_settings": [
    "index.refresh_interval"
  ]
}


Thanks

**Comment by willyborankin** [comment] 2022-07-04 18:54
I can't reproduce it with the same config. 
Could you please add into `log4j2.properties`: `rootLogger.level = trace` and try to restore the snapshot on your local node. Logging is verbose, so it is better to dump it into the file if the log file is too big, you can share it with me using the same link I sent you before.

**Comment by willyborankin** [comment] 2022-07-04 20:38
Hi @ycyr It seems like I got the problem. Can you set `base_path` to your repository settings and repeat the test?

**Comment by ycyr** [comment] 2022-07-04 21:20
Hi @willyborankin, I've put the file logs with rootLogger.level = trace  in the google share drive.  I've tried with base_path and doesn't anything.

**Comment by willyborankin** [comment] 2022-07-04 21:31
> Hi @willyborankin, I've put the file logs with rootLogger.level = trace in the google share drive. I've tried with base_path and doesn't anything.

Thank you @ycyr, will investigate tomorrow. Besides that, I had an idea. Since you did not add `base_path` property the underlying S3 plugin will read all paths in your bucket starting with `/` and if you have a lot of paths in it it could build a huge tree.

**Comment by willyborankin** [comment] 2022-07-05 08:05
HI @ycyr, I checked your logs.
Your index was restored successfully but its shard is in `UNASSIGNED` state, this means that data was restored but your cluster does not have room to start the shard. If one of the shard is in `UNASSIGNED` state you can't read data from it. 
You can read e.g. here https://www.datadoghq.com/blog/elasticsearch-unassigned-shards/ how to deal with `UNASSIGNED` shards. I can only confirm in this case that plugin works as expected. 
`
unassigned
2022-07-04T17:09:07.916119684-04:00 stdout F --------[restored_network-2022.06.19][0], node[null], [P], recovery_source[snapshot recovery [PApH7CLNTj-nTPYmOa8lNg] from aws-s3-encrypted-new:test4/EaJphKiyTD-Mug2H06aH6g], s[UNASSIGNED], unassigned_info[[reason=NEW_INDEX_RESTORED], at[2022-07-04T21:09:07.893Z], delayed=false, details[restore_source[aws-s3-encrypted-new/test4]], allocation_status[fetching_shard_data]]
`

**Comment by willyborankin** [comment] 2022-07-05 08:40
Beside that what from logs your node works with 3GB heap and S3 snapshotting uses 1GB for part size which could be a problem  if you restore + query + making snapshoting same time, most probably it was a reason why you got GC.

**Comment by ycyr** [comment] 2022-07-06 17:24
Hi @willyborankin,  I've tried several combinations of settings for buffer_size and chunk_size without real improvement :-( .

I tried with more powerful server, the restoring process seem to work, but it's taking forever. For example, for an index of 500mb, the restore took about 1h30. In comparison, in when I'm not using the encryption, the restore will done in 2-3 minutes.

I've created a test stack with docker-compose if you want to reproduce my setup. [(https://github.com/ycyr/opensearch-lab-test)](url) maybe if you be able to understand what I'm doing wrong.

Regards

**Comment by willyborankin** [comment] 2022-07-06 18:49
> Hi @willyborankin,  I've tried several combinations of settings for buffer_size and chunk_size without real improvement :-( .
> 
> I tried with more powerful server and the restoring process seem to work, but it's taking forever. For example, for an index of 500mb, the restore took about 1h30. In comparison, in when I'm not using the encryption, the restore will done in 2-3 minutes.
> 
> I've created a test stack with docker-compose if you want to reproduce my setup. [(https://github.com/ycyr/opensearch-lab-test](https://github.com/ycyr/opensearch-lab-test) maybe if you be able to understand what I'm doing wrong.
> 
> Regards
> 
> 
> 

Hi @ycyr, so it works but very slow. Interesting we use similar solution and restoration of 1TB snapshot takes 1 hour. I'm puzzled. Thank you for the config you provided I will play with it. BTW did you use default crypto provider or amazon corretto?

**Comment by willyborankin** [comment] 2022-07-06 18:51
> > Hi @willyborankin,  I've tried several combinations of settings for buffer_size and chunk_size without real improvement :-( .
> > 
> > I tried with more powerful server and the restoring process seem to work, but it's taking forever. For example, for an index of 500mb, the restore took about 1h30. In comparison, in when I'm not using the encryption, the restore will done in 2-3 minutes.
> > 
> > I've created a test stack with docker-compose if you want to reproduce my setup. [(https://github.com/ycyr/opensearch-lab-test](https://github.com/ycyr/opensearch-lab-test) maybe if you be able to understand what I'm doing wrong.
> > 
> > Regards
> > 
> > 
> > 
> 
> Hi @ycyr, so it works but very slow. Interesting we use similar solution and restoration of 1TB snapshot takes 1 hour. I'm puzzled. Thank you for the config you provided I will play with it. BTW did you use default crypto provider or amazon corretto?

And one more thing. Do you use security plugin?  I saw an issue in openseach github repo that restoration of a snapshot is slow with it. I've never tested it with security plugin since it is impossible to use in commercial systems so far.

**Comment by ycyr** [comment] 2022-07-06 19:23
@willyborankin 

Yes I'm using Amazon Corretto Crypto Provider and the Opensearch security plugin. 

Concerning the security plugin, I don't have any issue when I'm doing a restore from a s3 repository without the encryption plugin.

Also, don't know it's will help you but when I'm looking the bandwidth speed during the restore, the speed is about 1Mb/s with an encrypted repository, and it's above 40Mb/s with the unencrypted repository.

**Comment by willyborankin** [comment] 2022-07-06 19:25
> @willyborankin 
> 
> Yes I'm using Amazon Corretto Crypto Provider and the Opensearch security plugin. 
> 
> Concerning the security plugin, I don't have any issue when I'm doing a restore from a s3 repository without the encryption plugin.
> 
> Also, don't know it's will help you but when I'm looking the bandwidth speed during the restore, the speed is about 1Mb/s with an encrypted repository, and it's above 40Mb/s with the unencrypted repository.  
> 
Oooo it could be the root cause. Will play with it tomorrow morning.

**Comment by willyborankin** [comment] 2022-07-06 19:39
> > @willyborankin
> > Yes I'm using Amazon Corretto Crypto Provider and the Opensearch security plugin.
> > Concerning the security plugin, I don't have any issue when I'm doing a restore from a s3 repository without the encryption plugin.
> > Also, don't know it's will help you but when I'm looking the bandwidth speed during the restore, the speed is about 1Mb/s with an encrypted repository, and it's above 40Mb/s with the unencrypted repository.
> 
> Oooo it could be the root cause. Will play with it tomorrow morning.

According this [artical](https://aws.amazon.com/blogs/opensource/introducing-amazon-corretto-crypto-provider-accp/) corretto must be faster.

**Comment by willyborankin** [comment] 2022-07-06 19:42
> Also, I don't understand you said it is impossible to use the Opensearch security in commercial system. The Opensearch security plugin is not under the Apache License ?

Yes this a court between 2 companies about same code in ES security plugin and OS security plugin. So it is in a gray zone so far.

**Comment by reta** [comment] 2022-07-07 14:47
> I tried with more powerful server and the restoring process seem to work, but it's taking forever. For example, for an index of 500mb, the restore took about 1h30. In comparison, in when I'm not using the encryption, the restore will done in 2-3 minutes.

@ycyr could you please share the hot threads [1] during the encrypted snapshot restoration? Also, could you please clarify if you run Opensearch in containers or not, how many CPUs are allocated to the Opensearch (on VM or container), thank you.

[1] https://opensearch.org/docs/2.0/opensearch/rest-api/nodes-apis/nodes-hot-threads/

**Comment by ycyr** [comment] 2022-07-07 17:58
Hi @willyborankin,

For restoring an index of 223Mb

- Output hot threads after 2min [https://gist.github.com/ycyr/80a9a4179dbadcc708b1f96863677db6](url)
- Output hot threads after 5 min [https://gist.github.com/ycyr/8470b1207198b7b4edc21a70767e2eb0](url)

In this case, I'm running opensearch under docker (compose) on the physical server has 24 cores and all containers can see all the cpu cores.

Yanick

**Comment by reta** [comment] 2022-07-07 18:07
@ycyr ah, could be this one [1], I would expect to see BouncyCastle provider here not JCE, @willyborankin any hints why it is not picked up?

[1] http://aredko.blogspot.com/2020/04/the-crypto-quirks-using-jdks-cipher.html

**Comment by willyborankin** [comment] 2022-07-07 20:29
I think it is a collision between a security plugin which adds BC provider (https://github.com/opensearch-project/security/blob/be876c0078b23dc6567f6bd2f585d5f14245b201/src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java#L306) and an encryption plugin. I need to think how to do it better and play with it, but so far you can exclude Corretto it uses BC by default or the way how I add security provider is messy and it breaks the security providers order.

**Comment by ycyr** [comment] 2022-07-08 14:42
Hi @willyborankin, I've tried without Corretto and the behavior is the same. The restore takes forever. For 1.5 gb index, after 10 min, the restore was about 7.5%.  The only difference I've noticed is CPU load. Without Corretto,  Opensearch was using 25% more cpu during the restore.

**Comment by willyborankin** [comment] 2022-07-08 16:18
Hi @ycyr, yes securoty plugin mess up order and it was a mistake when I decided to relay on the security providers order. I changed code here: https://github.com/aiven/encrypted-repository-opensearch/pull/34.
I will prepare build for `2.0.1`, `2.1.0` and `1.3.3` versions after it's been merged.

**Comment by ycyr** [comment] 2022-07-11 21:16
Hi @willyborankin, I've tried in my lab your new releases on an Opensearch cluster (2.0.1 and 1.3.3), and it's working very well. 

Just to give some metrics, I've made a snapshot  of an 1.9g index in an unencrypted repository and in an encrypted repo:

_Unencrypted repo:_

Time snapshot: 45 sec
Time  restore:  46 sec

_Encrypted repo:_

Time snapshot:  61 sec
Time restore:  90 sec

I need to do some testing in my production cluster  and with bigger indices, but I'm very happy with preliminary results.

Thank you very.

**Comment by willyborankin** [comment] 2022-07-12 07:43
Hi @ycyr, perfect news. I did the same testing. I think we can close this issue right?

**Closed** 2022-07-12 11:24 UTC

**Comment by willyborankin** [comment] 2022-07-12 11:32
> Hi @willyborankin, we can close this issue. Thanks again

Hi @ycyr, no worries. The reason why we decided to exclude Amazon Corretto is this,  https://github.com/corretto/amazon-corretto-crypto-provider/issues/231. The performance is better, but memory allocation is too aggressive, so I'm investigating the possibility of improving speed but it will take time, so stay tuned.
